---
common_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gpg
  - gnupg
  - software-properties-common
  - python3-pip

common_kernel_modules:
  - overlay
  - br_netfilter

common_sysctl_params:
  net.bridge.bridge-nf-call-iptables: 1
  net.bridge.bridge-nf-call-ip6tables: 1
  net.ipv4.ip_forward: 1
