apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ansibleai.saApi" . }}
  labels:
    {{- include "ansibleai.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
automountServiceAccountToken: {{ .Values.serviceAccounts.automountServiceAccountToken }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ansibleai.saWorker" . }}
  labels:
    {{- include "ansibleai.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
automountServiceAccountToken: {{ .Values.serviceAccounts.automountServiceAccountToken }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ansibleai.saMigrate" . }}
  labels:
    {{- include "ansibleai.labels" . | nindent 4 }}
    app.kubernetes.io/component: migrate
automountServiceAccountToken: {{ .Values.serviceAccounts.automountServiceAccountToken }}
